const data = {
    products:[
        {
            name: 'Over Shirt',
            slug: 'over-shirt',
            image: '/images/shirt1.jpg',
            banner: '/images/banner1.png',
            price: 2899,
            brand: 'Nike',
            description: 'A popular trendy shirt',
            category: 'Shirts',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            isFeatured: true,
        },
        {
            name: 'Fit Shirt',
            slug: 'fit-shirt',
            image: '/images/shirt2.jpg',
            banner: '/images/banner2.png',
            price: 2499,
            brand: 'Zara',
            description: 'A popular trendy shirt',
            category: 'Shirts',
            rating: 4.2,
            numReviews: 12,
            countInStock: 16,
            isFeatured: true,
        },
        {
            name: 'Slim Shirt',
            slug: 'slim-shirt',
            image: '/images/shirt3.jpg',
            banner: '/images/banner3.png',
            price: 1699,
            brand: 'Raymond',
            description: 'A popular trendy shirt',
            category: 'Shirts',
            rating: 4.0,
            numReviews: 6,
            countInStock: 20,
            //isFeatured: true,
        },
        {
            name: 'Golf Pants',
            slug: 'golf-pants',
            image: '/images/pants1.jpg',
            //banner: '/images/banner1.png',
            price: 2599,
            brand: 'OffDuty',
            description: 'A stylish looking pant',
            category: 'Pants',
            rating: 4.7,
            numReviews: 19,
            countInStock: 32,
            //isFeatured: true,
        },
        {
            name: 'Fit Pants',
            slug: 'fit-pants',
            image: '/images/pants2.jpg',
            //banner: '/images/banner1.png',
            price: 1999,
            brand: 'Oliver',
            description: 'A stylish looking pant',
            category: 'Pants',
            rating: 4.1,
            numReviews: 15,
            countInStock: 26,
            //isFeatured: true,
        },
        {
            name: 'Classic Pants',
            slug: 'classic-pants',
            image: '/images/pants3.jpg',
            //banner: '/images/banner1.png',
            price: 1899,
            brand: 'Louis Vuitton',
            description: 'A stylish looking pant',
            category: 'Pants',
            rating: 4.6,
            numReviews: 10,
            countInStock: 8,
            //isFeatured: true,
        },
    ]
}

export default data